// drug_ui/src/views/Login/Login.vue
<script setup>
import { ref } from 'vue'
import bgImage from '@/assets/images/bg-2.jpg'
import { httpLogin } from '@/api/login'
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()

let form = ref({
    userName: '',
    userPassword: ''
})

function handleLogin() {
    console.log('click', form)
    httpLogin(form.value)
        .then(res => {
            // 保存 token
            const token = res.data.token || ''
            console.log("🚀 ~ file: Login.vue:22 ~ handleLogin ~ token:", token)
            localStorage.setItem('pro__token', token)


            // 保存 userInfo
            const userInfo = res.data.userInfo || {}
            console.log("🚀 ~ file: Login.vue:26 ~ handleLogin ~ userInfo:", userInfo)
            localStorage.setItem('pro__userInfo', JSON.stringify(userInfo))

            router.push({
                path: '/drugCatelogue'
                // name: 'drugCatelogue',
                // query: {
                //     ...route.query,
                //     ...query,
                // },
            })
        })
        .catch(err => {
            console.log("🚀 ~ file: Login.vue:21 ~ handleLogin ~ err:", err)
        })
}
</script>

<template>
    <el-image :src="bgImage" class="bg-image">
    </el-image>
    <div class="page">
        <div class="login-row">
            <h2>药品库存管理系统</h2>
            <el-form :model="form" label-suffix=":" label-width="70" class="form-row">
                <el-form-item label="用户名">
                    <el-input v-model="form.userName"></el-input>
                </el-form-item>
                <el-form-item label="密码">
                    <el-input v-model="form.userPassword"></el-input>
                </el-form-item>
                <el-row type="flex" justify="center">
                    <el-button type="primary" @click="handleLogin">登 录</el-button>
                </el-row>
            </el-form>
        </div>
    </div>
</template>

<style scoped>
.bg-image {
    width: 100%;
    height: 100%;
    position: absolute;
}

.page {
    width: 100%;
    height: 100%;
    position: relative;
    display: flex;
    justify-content: center;
    align-items: center;
}

.login-row {
    width: 380px;
    height: 248px;
    border: 2px solid rgba(0, 0, 0, 0.4);
    border-radius: 4px;
    box-shadow: rgba(0, 0, 0, 0.12) 0px 0px 12px 0px;
    z-index: 100;
    background-color: rgba(255, 255, 255, 0.6);

    h2 {
        text-align: center;
    }
}

.form-row {
    padding: 0 32px;
}
</style>

// drug_react_ecommerce/src/views/Login/Login.tsx
import { useState } from 'react'
import { useNavigate, Link } from "react-router-dom";
import { message } from 'antd';

import bgImage from 'images/bg-2.jpg'
import { HttpLogin } from '@/api/login'

export default function Login() {
    const [messageApi, contextHolder] = message.useMessage();

    const [userName, setUserName] = useState('')
    const [userPassword, setUserPassword] = useState('')

    const navigate = useNavigate();
    // navigate("/session-timed-out");

    function handleUserNameChange(e: any) {
        const value = e.target.value
        setUserName(value)
    }
    function handlePasswordChange(e: any) {
        const value = e.target.value
        setUserPassword(value)
    }

    function handleSubmit() {
        console.log(userName)
        console.log(userPassword)
        if (userName && userPassword) {
            const params = {
                userName,
                userPassword
            }
            HttpLogin(params)
                .then((res: any) => {
                    res = res.data || {
                        userInfo: {},
                        token: ''
                    }

                    localStorage.setItem('pro__ecommerce__token', res.token)
                    localStorage.setItem('pro__ecommerce__userInfo', JSON.stringify(res.userInfo))

                    navigate('/home')

                })
        } else {
            messageApi.info('请检查用户名与密码!');
        }
    }

    return (
        <div className="bg-white w-screen h-screen relative">
            {contextHolder}
            <img
                src={bgImage}
                className="h-full w-full absolute object-cover object-center lg:h-full lg:w-full"
            />

            <div className="w-[600px] h-[400px] absolute top-0 bottom-0 left-0 right-0 m-auto border border-gray-400 rounded-lg bg-gray-300/70 flex flex-col">
                <h2 className="text-center my-4 text-2xl ">登 录</h2>

                <div className="border flex-1 m-4 mt-0 p-4">
                    <div className="">
                        <label htmlFor="username" className="block text-sm font-medium leading-6 text-gray-900">
                            账户名:
                        </label>
                        <div className="mt-2">
                            <div className="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 ">
                                <input
                                    type="text"
                                    name="username"
                                    id="username"
                                    value={userName}
                                    onChange={handleUserNameChange}
                                    className="block flex-1 border-0 bg-white py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 "
                                    placeholder="请输入账户名"
                                />
                            </div>
                        </div>
                    </div>
                    <div className="mt-4">
                        <label htmlFor="userPassword" className="block text-sm font-medium leading-6 text-gray-900">
                            密码:
                        </label>
                        <div className="mt-2">
                            <div className="flex rounded-md shadow-sm ring-1 ring-inset ring-gray-300 ">
                                <input
                                    type="text"
                                    name="userPassword"
                                    id="userPassword"
                                    value={userPassword}
                                    onChange={handlePasswordChange}
                                    className="block flex-1 border-0 bg-white py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 "
                                    placeholder="请输入密码"
                                />
                            </div>
                        </div>
                    </div>
                    <div className="my-4 flex justify-end">
                        <Link to='/register' className='no-underline'>注册</Link>
                    </div>
                    <div className="mt-6 flex justify-center">
                        <button className="w-4/5 h-10 border rounded-lg bg-indigo-500 text-white" onClick={() => handleSubmit()}>
                            登 录
                        </button>
                    </div>
                </div>
            </div>
        </div>
    )

}
